### ISSUE TITLE
Implicit H handling on nitrogen

### ISSUE THREAD

**Issue by schatzsc** [metamolecular/balsadoc#26]
![NR4](https://user-images.githubusercontent.com/88166560/176556039-c9924d6e-e445-4a66-9c38-34a6a0fcbd72.png)

Is there any real example for such a pentavalent nitrogen center? There are about 550 examples of N atoms with a coordination number (= "valence") of five in the Cambridge Structural Database, but most of these are clusters with nitrogen bonded to small 1st or 2nd row metals such as lithium. A rare example which does not match this description is here:

<img width="950" alt="n4" src="https://user-images.githubusercontent.com/88166560/176556829-72a25c5c-b6b9-42a9-b31c-fe682645f850.png">

Much more likely, you will find an ammonium cation:

Valence [= coordination number]: 1+1+1+1=4
Subvalence: 4-4 = 0
Implicit H: 0

**Comment by rapodaca** [comment]
The main problem with changing the valence table (even by deleting entries) is that is causes hydrogen counts to differ in SMILES and Balsa. For example, the string:

"N(C)(C)(C)C"

would have an implicit hydrogen count of 1 in SMILES but 0 in Balsa. No matter how unrealistic such a molecule might be, this discrepancy would make Balsa incompatible with SMILES in a surprising way.

Closing this issue for now until a more compelling reason to drop the 5 valence comes to light.
