### ISSUE TITLE
Handling of atoms which do not follow octet rule?

### ISSUE THREAD

**Issue by schatzsc** [metamolecular/balsadoc#27]
How do you want to handle atoms which do not follow the octet rule?

Classical examples of 2nd row compounds are diborane (B2H6) and nitric oxide (NO). How do you want to make sure BALSA handles NO and HNO differently?

And more importantly, how to handle diborane with its 3c2e bonds, which cannot be expressed in terms of Lewis formulas?

https://en.wikipedia.org/wiki/Diborane
https://en.wikipedia.org/wiki/Nitric_oxide
https://en.wikipedia.org/wiki/Nitroxyl

**Comment by rapodaca** [comment]
Multi-centered bonding as in diborane is out of scope. A bond can have exactly two atoms and 2, 4, or 6 electrons. There are no exceptions. This is inherited from SMILES.

Many molecules will not be representable by Balsa for this reason. It's a tradeoff. More complex languages can address more chemical space, but they are also more complex and harder to implement correctly.

When implicit hydrogen counting fails, virtual hydrogen count can be used. For example, nitric oxide can be represented as "[N]=[O]". Nitroxyl would could use implicit hydrogen counting: "N=O".

For diborane, one option is "B.B".

If more sophistication notions of bonding are needed, something other than Balsa should be used.

**Comment by rapodaca** [comment]
Closing this issue as out of scope.
